/*
╔════════════════════════════════════════════════════════════════════════════════════╗
║                                                                                    ║
║   Copyright (c) 2020-25 https://prrvchr.github.io                                  ║
║                                                                                    ║
║   Permission is hereby granted, free of charge, to any person obtaining            ║
║   a copy of this software and associated documentation files (the "Software"),     ║
║   to deal in the Software without restriction, including without limitation        ║
║   the rights to use, copy, modify, merge, publish, distribute, sublicense,         ║
║   and/or sell copies of the Software, and to permit persons to whom the Software   ║
║   is furnished to do so, subject to the following conditions:                      ║
║                                                                                    ║
║   The above copyright notice and this permission notice shall be included in       ║
║   all copies or substantial portions of the Software.                              ║
║                                                                                    ║
║   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,                  ║
║   EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES                  ║
║   OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.        ║
║   IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY             ║
║   CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,             ║
║   TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE       ║
║   OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                                    ║
║                                                                                    ║
╚════════════════════════════════════════════════════════════════════════════════════╝
 */

#ifndef __com_sun_star_mail_XImapService_idl__
#define __com_sun_star_mail_XImapService_idl__

#include <com/sun/star/mail/XMailService.idl>
#include <com/sun/star/mail/XMailMessage.idl>
#include <com/sun/star/io/NotConnectedException.idl>
#include <com/sun/star/mail/MailException.idl>
#include <com/sun/star/mail/SendMailMessageFailedException.idl>
#include <com/sun/star/datatransfer/UnsupportedFlavorException.idl>

module com { module sun { module star { module mail {

/** This is an extension to the interface XMailService.

    Be careful: use of XMailService.getSupportedConnectionTypes()
    interface is modified as follows:
    
        Returns all connection types which are supported to
        connect to the mail service. At least support insecure
        connections must be supported. Currently defined
        connection types are (the values should be handled
        case insensitive):
        "Insecure" - insecure connections
        "SSL"      - Secure Socket Layer 2.0/3.0 based connection
        "TLS"      - Transport Layer Security 1.0 based connection

    @since LibreOffice 24.02
*/

interface XImapService : XMailService
{

    /**
        Returns all authentication types which are supported to
        connect to the mail service. At least support None / Login
        authentications must be supported. Currently defined
        authentication types are (the values should be handled
        case insensitive):
        "None"   - no authentication required
        "Login"  - login/password based authentication
        "OAuth2" - OAuth 2.0 based authentication

        @returns
        a sequence of supported authentication types.
    */
    sequence<string> getSupportedAuthenticationTypes();

    string getSentFolder()
        raises(com::sun::star::io::NotConnectedException);

    boolean hasFolder([in] string Folder)
        raises(com::sun::star::io::NotConnectedException);

    void uploadMessage([in] string Folder,
                       [in] com::sun::star::mail::XMailMessage MailMessage)
        raises(com::sun::star::io::NotConnectedException, com::sun::star::mail::SendMailMessageFailedException, com::sun::star::mail::MailException, com::sun::star::datatransfer::UnsupportedFlavorException);


};

}; }; }; };

#endif
