#ifndef __com_sun_star_mail_XMailService2_idl__
#define __com_sun_star_mail_XMailService2_idl__

#include <com/sun/star/mail/XMailService.idl>

module com { module sun { module star { module mail {

interface XMailService2: com::sun::star::mail::XMailService
{

    sequence<string> getSupportedAuthenticationTypes();

};

}; }; }; };

#endif
